### ISSUE TITLE
Add neural networks support

### ISSUE THREAD

**Issue by myerspat** [aims-umich/pyMAISE#15]
## Background
Continue adding support for more models. Added generalized neural networks model for sequential, dense, Adam optimized NN.

## Tasks
- [x] Add NN modeling support
- [x] Add MIT control rod data
- [x] Add MIT control rod data example for NN hyper-parameter tuning

## Definition of Done
NN is supported and runs for the MIT control rod data.
