### ISSUE TITLE
NERS 551: Rod Eject Sensitivity Analysis Data

### ISSUE THREAD

**Issue by myerspat** [aims-umich/pyMAISE#28]
## Background
For the NERS 551 project, we will develop a data set based on perturbation in a PWR rod ejection scenario. This data will then be used to train a surrogate model with which we'll conduct the sensitivity analysis. The perturbed input parameter distribution is:

| Parameter | PARCS Card | Uncertainty Distribution |
|---|----|----|
| Rod Worth | `move_bank` | U[`rho_max` - 0.15 * `rho_max`, `rho_max`] |
| Beta | `dnp_beta` | N[5%] |
| Gap conductance | `h_gap` | N[20%] |
| Gamma | `gamma_frac`| N[20%] |

Rod worth needs to be mapped to the bank position. In the input file, beta is given in the six-group form, perturb beta globally and maintain constant fractions. 

The parameters that need to be read from the output files are

- Max centerline fuel temperature
- Average outlet temperature
- Max power
- Pulse width

The four input parameter distributions should be sampled, changed in the input file, and run through PARCS. The output should be parsed for the three outputs. **Save the reactivity and power for each time step up to 3 seconds as well.**

## Tasks
- [x] Find ejected rod worth as a function of bank position so this can be linearly interpolated for input file generation
- [x] Generate 1000 data points by perturbing the four input parameters all at once and extract the three outputs, ensure the inputs and outputs are collected in separate CSV files
- [x] Put the data in the `pyMAISE/data` directory and create a data handler in `pyMAISE/data/_handler.py`

## Definition of Done
The data is correctly generated, exits in the `pyMAISE/data` directory, has an associate handler function, and all tests pass.
