### ISSUE TITLE
NERS551: Jupyter notebook for transient rod ejection accident

### ISSUE THREAD

**Issue by myerspat** [aims-umich/pyMAISE#30]
## Background
We have data for NERS551 rod ejection accident (REA), now we need to create pyMAISE benchmark for calculating sensitivity coefficients. The distributions and information of the project is shown in issue #28. 

## Tasks
- [x] Read and process data, you can read in the data using the `load_rea` function
- [x] Hyper-parameter tune all supported models (SVR is the only one not supported for this type of data set)
- [x] Compare models and find best one
- [x] Conduct sensitivity analysis to determine first order sensitivity coefficients

## Definition of Done
A corresponding Jupyter notebook benchmark is in `docs/source/examples` and includes analysis of sensitivity coefficients for the four outputs.
