### ISSUE TITLE
Comparison of pyMAISE with other AutoML libraries

### ISSUE THREAD

**Issue by myerspat** [aims-umich/pyMAISE#66]
## Background
We must demonstrate that pyMAISE can produce results comparable to those of other AutoML libraries. We want to test three libraries on the HTGR benchmark (full dataset including 3004 samples). You can add this as a subsection within the HTGR benchmark. The three libraries are

- [auto-sklearn](https://automl.github.io/auto-sklearn/master/#),
- [AutoKeras](https://autokeras.com/),
- [H2O AutoML](https://h2o.ai/platform/h2o-automl/).

## Tasks

Show pyMAISE produces similar results to the three AutoML libraries:

- [ ] [auto-sklearn](https://automl.github.io/auto-sklearn/master/#),
- [ ] [AutoKeras](https://autokeras.com/),
- [ ] [H2O AutoML/](https://h2o.ai/platform/h2o-automl/).

## Definition of Done

All models produced by pyMAISE are compared with the models produced by the above packages. This comparison is discussed in detail on the [HTGR Jupyter Notebook](https://pymaise.readthedocs.io/en/latest/benchmarks/HTGR_microreactor.html).
